config/routes.rb
SampleApp::Application.routes.draw do
  resources :blocks

  resources :block_types

  resources :navgations

  resources :nav_types

  resources :app_versions

  resources :users do
    member do
      get :following, :followers, :company
      
    end
  end
  
  resources :apps 
  resources :nav_types
  
  
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/navgation.rb
class Navgation < ActiveRecord::Base
  belongs_to :app
  
end

app/controllers/navgations_controller.rb
class NavgationsController < ApplicationController
  before_action :set_navgation, only: [:show, :edit, :update, :destroy]

  # GET /navgations
  # GET /navgations.json
  def index
    @navgations = Navgation.all
  end

  # GET /navgations/1
  # GET /navgations/1.json
  def show
  end

  # GET /navgations/new
  def new
    @navgation = Navgation.new
  end

  # GET /navgations/1/edit
  def edit
  end

  # POST /navgations
  # POST /navgations.json
  def create
    @navgation = Navgation.new(navgation_params)

    respond_to do |format|
      if @navgation.save
        format.html { redirect_to @navgation, notice: 'Navgation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @navgation }
      else
        format.html { render action: 'new' }
        format.json { render json: @navgation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /navgations/1
  # PATCH/PUT /navgations/1.json
  def update
    respond_to do |format|
      if @navgation.update(navgation_params)
        format.html { redirect_to @navgation, notice: 'Navgation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @navgation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navgations/1
  # DELETE /navgations/1.json
  def destroy
    @navgation.destroy
    respond_to do |format|
      format.html { redirect_to navgations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_navgation
      @navgation = Navgation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def navgation_params
      params.require(:navgation).permit(:app_id, :nav_type_id, :status)
    end
end

app/helpers/navgations_helper.rb
module NavgationsHelper
end

app/views/navgations/_form.html.erb
<%= form_for(@navgation) do |f| %>
  <% if @navgation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@navgation.errors.count, "error") %> prohibited this navgation from being saved:</h2>

      <ul>
      <% @navgation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :app_id %><br>
    <%= f.number_field :app_id %>
  </div>
  <div class="field">
    <%= f.label :nav_type_id %><br>
    <%= f.number_field :nav_type_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/navgations/edit.html.erb
<h1>Editing navgation</h1>

<%= render 'form' %>

<%= link_to 'Show', @navgation %> |
<%= link_to 'Back', navgations_path %>

app/views/navgations/index.html.erb
<h1>Listing navgations</h1>

<table>
  <thead>
    <tr>
      <th>App</th>
      <th>Nav type</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @navgations.each do |navgation| %>
      <tr>
        <td><%= navgation.app_id %></td>
        <td><%= navgation.nav_type_id %></td>
        <td><%= navgation.status %></td>
        <td><%= link_to 'Show', navgation %></td>
        <td><%= link_to 'Edit', edit_navgation_path(navgation) %></td>
        <td><%= link_to 'Destroy', navgation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Navgation', new_navgation_path %>

app/views/navgations/new.html.erb
<h1>New navgation</h1>

<%= render 'form' %>

<%= link_to 'Back', navgations_path %>

app/views/navgations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App:</strong>
  <%= @navgation.app_id %>
</p>

<p>
  <strong>Nav type:</strong>
  <%= @navgation.nav_type_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @navgation.status %>
</p>

<%= link_to 'Edit', edit_navgation_path(@navgation) %> |
<%= link_to 'Back', navgations_path %>