config/routes.rb
SampleApp::Application.routes.draw do
  resources :blocks

  resources :block_types

  resources :navgations

  resources :nav_types

  resources :app_versions

  resources :users do
    member do
      get :following, :followers, :company
      
    end
  end
  
  resources :apps 
  resources :nav_types
  
  
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/app_version.rb
class AppVersion < ActiveRecord::Base
  belongs_to :app
  
end

app/controllers/app_versions_controller.rb
class AppVersionsController < ApplicationController
  before_action :set_app_version, only: [:show, :edit, :update, :destroy]

  # GET /app_versions
  # GET /app_versions.json
  def index
    @app_versions = AppVersion.all
  end

  # GET /app_versions/1
  # GET /app_versions/1.json
  def show
  end

  # GET /app_versions/new
  def new
    @app_version = AppVersion.new
  end

  # GET /app_versions/1/edit
  def edit
  end

  # POST /app_versions
  # POST /app_versions.json
  def create
    @app_version = AppVersion.new(app_version_params)

    respond_to do |format|
      if @app_version.save
        format.html { redirect_to @app_version, notice: 'App version was successfully created.' }
        format.json { render action: 'show', status: :created, location: @app_version }
      else
        format.html { render action: 'new' }
        format.json { render json: @app_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_versions/1
  # PATCH/PUT /app_versions/1.json
  def update
    respond_to do |format|
      if @app_version.update(app_version_params)
        format.html { redirect_to @app_version, notice: 'App version was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @app_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_versions/1
  # DELETE /app_versions/1.json
  def destroy
    @app_version.destroy
    respond_to do |format|
      format.html { redirect_to app_versions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_version
      @app_version = AppVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_version_params
      params.require(:app_version).permit(:version_number, :url, :description)
    end
end

app/helpers/app_versions_helper.rb
module AppVersionsHelper
end

app/views/app_versions/_form.html.erb
<%= form_for(@app_version) do |f| %>
  <% if @app_version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_version.errors.count, "error") %> prohibited this app_version from being saved:</h2>

      <ul>
      <% @app_version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :version_number %><br>
    <%= f.text_field :version_number %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/app_versions/edit.html.erb
<h1>Editing app_version</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_version %> |
<%= link_to 'Back', app_versions_path %>

app/views/app_versions/index.html.erb
<h1>Listing app_versions</h1>

<table>
  <thead>
    <tr>
      <th>Version number</th>
      <th>Url</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @app_versions.each do |app_version| %>
      <tr>
        <td><%= app_version.version_number %></td>
        <td><%= app_version.url %></td>
        <td><%= app_version.description %></td>
        <td><%= link_to 'Show', app_version %></td>
        <td><%= link_to 'Edit', edit_app_version_path(app_version) %></td>
        <td><%= link_to 'Destroy', app_version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App version', new_app_version_path %>

app/views/app_versions/new.html.erb
<h1>New app_version</h1>

<%= render 'form' %>

<%= link_to 'Back', app_versions_path %>

app/views/app_versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Version number:</strong>
  <%= @app_version.version_number %>
</p>

<p>
  <strong>Url:</strong>
  <%= @app_version.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @app_version.description %>
</p>

<%= link_to 'Edit', edit_app_version_path(@app_version) %> |
<%= link_to 'Back', app_versions_path %>