config/routes.rb
SampleApp::Application.routes.draw do
  resources :blocks

  resources :block_types

  resources :navgations

  resources :nav_types

  resources :app_versions

  resources :users do
    member do
      get :following, :followers, :company
      
    end
  end
  
  resources :apps 
  resources :nav_types
  
  
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  
  has_many :block
  has_many :app_version
  has_many :navgation 
    
end

app/models/app_version.rb
class AppVersion < ActiveRecord::Base
  belongs_to :app
  
end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :app
  belongs_to :block_type
  
  
  
end

app/models/block_type.rb
class BlockType < ActiveRecord::Base
  has_many :blocks
  
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  # Returns microposts from the users being followed by the given user.
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          user_id: user.id)
  end
end

app/models/nav_type.rb
class NavType < ActiveRecord::Base
end

app/models/navgation.rb
class Navgation < ActiveRecord::Base
  belongs_to :app
  
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :apps
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end


  def company
    relationships.find_by(followed_id: other_user.id)
  end
  
  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :signed_in_user,
                only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: :destroy
  before_action :admin_user,     only: :destroy
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  def index
    
    @title = "所有的Apps"
    @user = current_user
    @apps = @user.apps.paginate(page: params[:page])
    
    render "index"
  end

  def update
    
    
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'app was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = current_user
    @app = App.find(params[:id])
    @app_version = AppVersion.find_by_app_id(@app.id)
    @navgations = Navgation.find_by_app_id(@app.id)
    
    @blocks = Block.where(:app_id =>@app.id).joins(:block_type)
  end

    
  def edit
    @user = current_user
    @app = App.find(params[:id])
    
  end
  
  private


  
  
  def set_app
    logger.info(params)
    @app = App.find(params[:id])
  end


  def app_params
    params.require(:app).permit(:name, :version_number, :description)
  end
  
  
  end

app/helpers/app_versions_helper.rb
module AppVersionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "iApp"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/block_typs_helper.rb
module BlockTypsHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/nav_types_helper.rb
module NavTypesHelper
end

app/helpers/navgations_helper.rb
module NavgationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app_version from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version_number %><br>
    <%= f.text_field :version_number %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/apps/apps.html.erb
<li>
	
  <%= link_to app.name, app %>

</li>

app/views/apps/edit.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
				
				<%= render 'form' %>
				
				
				<%= link_to 'Show', @app %> |
				<%= link_to 'Back', app_path %>
				 
      </h1>
    </section>
    
</div>

app/views/apps/index.html.erb
<% provide(:title, @user.name+ "所有产品" ) %>
<h1><%= @user.name + "的所有产品" %></h1>


<ul class="apps">
	
	
  <% @apps.each do |app| %>

		<li>
       <%= link_to app.name, app %> 
	

		</li>
    <% end %>


    <%= will_paginate @apps %>
</ul>

app/views/apps/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
         <%= @app.name   %>
      </h1>
    </section>
		
		
		
		
		<section>
		 		  	<p class="text-right"><%= link_to "Edit", edit_app_path, 
			                                class: "btn btn-primary right" %></p>
					<strong> Info </strong>
					<span>
	          sku_number: <%= @app.sku_number %>
					</span>	
							
					<% if @app_version %>
					<span>
	
						version_number:<%= @app_version.version_number %>
					</span>	
						<span>
				    description: <%= @app_version.description %>
					</span>	

					<% end %>			

		</section>
 	<section>
  	<p class="text-right"><%= link_to "Edit", edit_app_path, 
                              class: "btn btn-primary right" %></p>
		<strong> Navgation </strong>
		<span>
      Navgation_type: <%= @navgations.id %>
		</span>	
  
	
	</section>
	 
 	<section>

		<strong> blocks </strong>

		<p class="text-right"><%= link_to "Edit", edit_app_path, 
		                              class: "btn btn-primary  " %></p>
<% @blocks.each do |block| %>

		<span>
      模块的名称: <%= block.id %>   	
		</span>	
  
	
	<% end %>
	
</section>
	
</aside>


<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
    in Section A.
  </ul>
  <div class="tab-content">
   in Section A.
  </div>
	
  <ul class="nav nav-tabs">
    in Section A.
  </ul>
  <div class="tab-content">
    in Section A.
  </div>
</div>


	
</div>

app/views/block_types/_form.html.erb
<%= form_for(@block_type) do |f| %>
  <% if @block_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block_type.errors.count, "error") %> prohibited this block_type from being saved:</h2>

      <ul>
      <% @block_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :show_name %><br>
    <%= f.text_field :show_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/block_types/edit.html.erb
<h1>Editing block_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @block_type %> |
<%= link_to 'Back', block_types_path %>

app/views/block_types/index.html.erb
<h1>Listing block_types</h1>

<table>
  <thead>
    <tr>
      <th>Show name</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @block_types.each do |block_type| %>
      <tr>
        <td><%= block_type.show_name %></td>
        <td><%= block_type.name %></td>
        <td><%= link_to 'Show', block_type %></td>
        <td><%= link_to 'Edit', edit_block_type_path(block_type) %></td>
        <td><%= link_to 'Destroy', block_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Block typ', new_block_type_path %>

app/views/block_types/new.html.erb
<h1>New block_type</h1>

<%= render 'form' %>

<%= link_to 'Back', block_types_path %>

app/views/block_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Show name:</strong>
  <%= @block_type.show_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @block_type.name %>
</p>

<%= link_to 'Edit', edit_block_type_path(@block_type) %> |
<%= link_to 'Back', block_types_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>  
</h1>

<span>
  <%= link_to "我的公司信息", company_user_path(current_user) %>
</span>
<span>
  <%= link_to "我的Apps", apps_path %>
</span>

<span>
  <!-- <%= pluralize(current_user.microposts.count, "micropost") %> -->
</span>