config/routes.rb
SampleApp::Application.routes.draw do
  resources :blocks

  resources :block_types

  resources :navgations

  resources :nav_types

  resources :app_versions

  resources :users do
    member do
      get :following, :followers, :company
      
    end
  end
  
  resources :apps 
  resources :nav_types
  
  
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/controllers/nav_types_controller.rb
class NavTypesController < ApplicationController
  before_action :set_nav_type, only: [:show, :edit, :update, :destroy]

  # GET /nav_types
  # GET /nav_types.json
  def index
    @nav_types = NavType.all
  end

  # GET /nav_types/1
  # GET /nav_types/1.json
  def show
  end

  # GET /nav_types/new
  def new
    @nav_type = NavType.new
  end

  # GET /nav_types/1/edit
  def edit
  end

  # POST /nav_types
  # POST /nav_types.json
  def create
    @nav_type = NavType.new(nav_type_params)

    respond_to do |format|
      if @nav_type.save
        format.html { redirect_to @nav_type, notice: 'Nav type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @nav_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @nav_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nav_types/1
  # PATCH/PUT /nav_types/1.json
  def update
    respond_to do |format|
      if @nav_type.update(nav_type_params)
        format.html { redirect_to @nav_type, notice: 'Nav type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @nav_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nav_types/1
  # DELETE /nav_types/1.json
  def destroy
    @nav_type.destroy
    respond_to do |format|
      format.html { redirect_to nav_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nav_type
      @nav_type = NavType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nav_type_params
      params.require(:nav_type).permit(:name, :show_name, :pic)
    end
end

app/helpers/nav_types_helper.rb
module NavTypesHelper
end

app/views/nav_types/_form.html.erb
<%= form_for(@nav_type) do |f| %>
  <% if @nav_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nav_type.errors.count, "error") %> prohibited this nav_type from being saved:</h2>

      <ul>
      <% @nav_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :show_name %><br>
    <%= f.text_field :show_name %>
  </div>
  <div class="field">
    <%= f.label :pic %><br>
    <%= f.text_field :pic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nav_types/edit.html.erb
<h1>Editing nav_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @nav_type %> |
<%= link_to 'Back', nav_types_path %>

app/views/nav_types/index.html.erb
<h1>Listing nav_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Show name</th>
      <th>Pic</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @nav_types.each do |nav_type| %>
      <tr>
        <td><%= nav_type.name %></td>
        <td><%= nav_type.show_name %></td>
        <td><%= nav_type.pic %></td>
        <td><%= link_to 'Show', nav_type %></td>
        <td><%= link_to 'Edit', edit_nav_type_path(nav_type) %></td>
        <td><%= link_to 'Destroy', nav_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nav type', new_nav_type_path %>

app/views/nav_types/new.html.erb
<h1>New nav_type</h1>

<%= render 'form' %>

<%= link_to 'Back', nav_types_path %>

app/views/nav_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nav_type.name %>
</p>

<p>
  <strong>Show name:</strong>
  <%= @nav_type.show_name %>
</p>

<p>
  <strong>Pic:</strong>
  <%= @nav_type.pic %>
</p>

<%= link_to 'Edit', edit_nav_type_path(@nav_type) %> |
<%= link_to 'Back', nav_types_path %>